name: Deploy Worker

on:
  push:
  workflow_dispatch:

jobs:
  deploy-to-cloudflare:
    runs-on: ubuntu-latest
    name: Automatic Cloudflare Deploy
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Enable corepack
        run: corepack enable

      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Update wrangler.toml Name Field
        run: |
          branch_name=$(echo '${{ github.event.ref }}' | sed 's#refs/heads/##' | sed 's#[^a-zA-Z0-9]#-#g')
          # Extract base name from wrangler.toml
          base_name=$(grep '^name = ' wrangler.toml | sed 's/^name = "\(.*\)"$/\1/')
          # Concatenate branch name with base name
          new_name="${base_name}-${branch_name}"
          # Truncate the new name to 63 characters for RFC 1035
          new_name=$(echo "$new_name" | cut -c 1-63)
          # Update the wrangler.toml file
          sed -i "s/^name = .*/name = \"$new_name\"/" wrangler.toml
          echo "Updated wrangler.toml name to: $new_name"

      - name: Deploy with Wrangler
        id: wrangler_deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.87.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            SUPABASE_URL
            SUPABASE_KEY
            CLOUDFLARE_ACCOUNT_ID
            CLOUDFLARE_API_TOKEN
            ${{ secrets.KERNEL_PUBLIC_KEY && secrets.KERNEL_PUBLIC_KEY != '' && 'KERNEL_PUBLIC_KEY' || '' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}

      - name: Write Deployment URL to Summary
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.wrangler_deploy.outputs.deployment-url }}" >> $GITHUB_STEP_SUMMARY
